<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleStore.Catalog.API.Client\SimpleStore.Catalog.API.Client.csproj" />
    <ProjectReference Include="..\SimpleStore.Data\SimpleStore.Data.csproj" />
    <ProjectReference Include="..\SimpleStore.ServiceDefaults\SimpleStore.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
