using System.Diagnostics;
using MassTransit;
using SimpleStore.Checkout.API.Timeouts;
using SimpleStore.Contracts;

namespace SimpleStore.Checkout.API.Sagas;

// MassTransit Saga State Machine orchestrating checkout (v12 — adds the payment step + compensation):
//
//   Initial        --OrderSubmitted--> AwaitingStock   (publish ReserveStockRequested, schedule stock timeout)
//   AwaitingStock  --StockReserved--> AwaitingPayment  (unschedule stock timeout, publish ProcessPaymentRequested,
//                                                        schedule payment timeout)
//   AwaitingStock  --StockReservationFailed--> Cancelled  (publish OrderCancelled, reason from msg)
//   AwaitingStock  --stock timeout--> Cancelled        (publish OrderCancelled, reason "ReservationTimeout")
//   AwaitingPayment --PaymentSucceeded--> Confirmed    (unschedule payment timeout, publish OrderConfirmed)
//   AwaitingPayment --PaymentFailed--> CompensatingStock  (unschedule payment timeout, store reason,
//                                                        publish StockReservationCancelRequested — the COMPENSATION)
//   AwaitingPayment --payment timeout--> CompensatingStock  (reason "PaymentTimeout", publish StockReservationCancelRequested)
//   CompensatingStock --StockReservationCancelled--> Cancelled  (publish OrderCancelled, reason from stored FailureReason)
//
// All events correlate on CorrelationId (generated by Order.API). Terminal states Finalize the saga.
//
// The CompensatingStock state is the point of this design: once stock has been reserved, a failed
// payment cannot simply cancel the order — the reserved stock must be released first. The saga waits
// for Inventory's StockReservationCancelledEventV1 (the compensation completing) before cancelling.
//
// TIMEOUT PERSISTENCE: both the ReservationTimeout and PaymentTimeout schedules are backed by a
// Quartz PERSISTENT ADO store in checkoutdb (the qrtz_* tables — see Program.cs). Scheduled timeouts
// SURVIVE a Checkout.API restart.
public sealed class CheckoutSagaStateMachine : MassTransitStateMachine<CheckoutSagaState>
{
    public State AwaitingStock { get; private set; } = null!;
    public State AwaitingPayment { get; private set; } = null!;
    public State CompensatingStock { get; private set; } = null!;
    public State Confirmed { get; private set; } = null!;
    public State Cancelled { get; private set; } = null!;

    public Event<OrderSubmittedEventV1> OrderSubmitted { get; private set; } = null!;
    public Event<StockReservedEventV1> StockReserved { get; private set; } = null!;
    public Event<StockReservationFailedEventV1> StockReservationFailed { get; private set; } = null!;
    public Event<PaymentSucceededEventV1> PaymentSucceeded { get; private set; } = null!;
    public Event<PaymentFailedEventV1> PaymentFailed { get; private set; } = null!;
    public Event<StockReservationCancelledEventV1> StockReservationCancelled { get; private set; } = null!;

    public Schedule<CheckoutSagaState, ReservationTimeoutExpired> ReservationTimeout { get; private set; } = null!;
    public Schedule<CheckoutSagaState, PaymentTimeoutExpired> PaymentTimeout { get; private set; } = null!;

    private readonly ILogger<CheckoutSagaStateMachine> _log;

    public CheckoutSagaStateMachine(IConfiguration configuration, ILogger<CheckoutSagaStateMachine> log)
    {
        _log = log;
        InstanceState(x => x.CurrentState);

        var reservationTimeoutSeconds = configuration.GetValue<int?>("Checkout:ReservationTimeoutSeconds") ?? 30;
        var paymentTimeoutSeconds = configuration.GetValue<int?>("Checkout:PaymentTimeoutSeconds") ?? 30;

        Event(() => OrderSubmitted, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));
        Event(() => StockReserved, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));
        Event(() => StockReservationFailed, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));
        Event(() => PaymentSucceeded, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));
        Event(() => PaymentFailed, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));
        Event(() => StockReservationCancelled, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));

        Schedule(() => ReservationTimeout, x => x.TimeoutTokenId, s =>
        {
            s.Delay = TimeSpan.FromSeconds(reservationTimeoutSeconds);
            s.Received = r => r.CorrelateById(ctx => ctx.Message.CorrelationId);
        });

        Schedule(() => PaymentTimeout, x => x.PaymentTimeoutTokenId, s =>
        {
            s.Delay = TimeSpan.FromSeconds(paymentTimeoutSeconds);
            s.Received = r => r.CorrelateById(ctx => ctx.Message.CorrelationId);
        });

        Initially(
            When(OrderSubmitted)
                .Then(ctx =>
                {
                    ctx.Saga.OrderId = ctx.Message.OrderId;
                    ctx.Saga.UserId = ctx.Message.UserId;
                    ctx.Saga.Amount = ctx.Message.TotalAmount;
                    ctx.Saga.ReservationId = Guid.NewGuid();
                    ctx.Saga.CreatedAt = DateTime.UtcNow;
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "Initial", "AwaitingStock", reason: null);
                })
                .Schedule(ReservationTimeout, ctx => new ReservationTimeoutExpired { CorrelationId = ctx.Saga.CorrelationId })
                .Publish(ctx => new ReserveStockRequestedEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    ReservationId = ctx.Saga.ReservationId,
                    OrderId = ctx.Saga.OrderId,
                    RequestedAt = DateTimeOffset.UtcNow,
                    Lines = ctx.Message.Items
                        .Select(i => new ReservationLineItem { ProductId = i.ProductId, Quantity = i.Quantity })
                        .ToList()
                })
                .TransitionTo(AwaitingStock));

        During(AwaitingStock,
            // Stock reserved — move on to payment instead of confirming directly (the v12 change).
            When(StockReserved)
                .Unschedule(ReservationTimeout)
                .Then(ctx =>
                {
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "AwaitingStock", "AwaitingPayment", reason: null);
                })
                .Schedule(PaymentTimeout, ctx => new PaymentTimeoutExpired { CorrelationId = ctx.Saga.CorrelationId })
                .Publish(ctx => new ProcessPaymentRequestedEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    UserId = ctx.Saga.UserId ?? string.Empty,
                    Amount = ctx.Saga.Amount,
                    RequestedAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(AwaitingPayment),
            When(StockReservationFailed)
                .Unschedule(ReservationTimeout)
                .Then(ctx =>
                {
                    ctx.Saga.FailureReason = ctx.Message.Reason;
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "AwaitingStock", "Cancelled", reason: ctx.Message.Reason);
                })
                .Publish(ctx => new OrderCancelledEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    Reason = ctx.Message.Reason,
                    CancelledAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Cancelled)
                .Finalize(),
            When(ReservationTimeout.Received)
                .Then(ctx =>
                {
                    ctx.Saga.FailureReason = "ReservationTimeout";
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "AwaitingStock", "Cancelled", reason: "ReservationTimeout");
                })
                .Publish(ctx => new OrderCancelledEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    Reason = "ReservationTimeout",
                    CancelledAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Cancelled)
                .Finalize());

        During(AwaitingPayment,
            // Payment charged — confirm the order. Stock stays decremented (the sale went through).
            When(PaymentSucceeded)
                .Unschedule(PaymentTimeout)
                .Then(ctx =>
                {
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "AwaitingPayment", "Confirmed", reason: null);
                })
                .Publish(ctx => new OrderConfirmedEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    ReservationId = ctx.Saga.ReservationId,
                    ConfirmedAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Confirmed)
                .Finalize(),
            // Payment failed — COMPENSATE: ask Inventory to release the reserved stock, then wait.
            When(PaymentFailed)
                .Unschedule(PaymentTimeout)
                .Then(ctx =>
                {
                    ctx.Saga.FailureReason = ctx.Message.Reason;
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "AwaitingPayment", "CompensatingStock", reason: ctx.Message.Reason);
                })
                .Publish(ctx => new StockReservationCancelRequestedEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    ReservationId = ctx.Saga.ReservationId,
                    OrderId = ctx.Saga.OrderId,
                    RequestedAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(CompensatingStock),
            When(PaymentTimeout.Received)
                .Then(ctx =>
                {
                    ctx.Saga.FailureReason = "PaymentTimeout";
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "AwaitingPayment", "CompensatingStock", reason: "PaymentTimeout");
                })
                .Publish(ctx => new StockReservationCancelRequestedEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    ReservationId = ctx.Saga.ReservationId,
                    OrderId = ctx.Saga.OrderId,
                    RequestedAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(CompensatingStock));

        During(CompensatingStock,
            // Stock released — the compensation completed, so the order can finally be cancelled.
            When(StockReservationCancelled)
                .Then(ctx =>
                {
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "CompensatingStock", "Cancelled", reason: ctx.Saga.FailureReason);
                })
                .Publish(ctx => new OrderCancelledEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    Reason = ctx.Saga.FailureReason ?? "PaymentFailed",
                    CancelledAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Cancelled)
                .Finalize());

        // Remove finalized saga instances from checkoutdb. Flip to keep them for audit.
        SetCompletedWhenFinalized();
    }

    private void LogTransition(CheckoutSagaState saga, string from, string to, string? reason)
    {
        // Logs feed the Aspire dashboard's log view; the tags feed the trace view. Both share
        // the same CorrelationId so filtering by it joins them up across all participating services.
        if (reason is null)
        {
            _log.LogInformation(
                "Saga {CorrelationId} order {OrderId}: {FromState} -> {ToState}.",
                saga.CorrelationId, saga.OrderId, from, to);
        }
        else
        {
            _log.LogInformation(
                "Saga {CorrelationId} order {OrderId}: {FromState} -> {ToState} ({Reason}).",
                saga.CorrelationId, saga.OrderId, from, to, reason);
        }

        var activity = Activity.Current;
        if (activity is not null)
        {
            activity.SetTag("saga.correlation_id", saga.CorrelationId);
            activity.SetTag("saga.order_id", saga.OrderId);
            activity.SetTag("saga.state.from", from);
            activity.SetTag("saga.state.to", to);
            if (reason is not null) activity.SetTag("saga.cancel_reason", reason);
        }
    }
}
