using MassTransit;

namespace SimpleStore.Checkout.API.Sagas;

// Persisted saga state (table checkout_saga_state in checkoutdb). The CorrelationId IS the saga
// key — it is generated by Order.API and threaded through every saga event.
public class CheckoutSagaState : SagaStateMachineInstance
{
    public Guid CorrelationId { get; set; }
    public string CurrentState { get; set; } = string.Empty;

    public int OrderId { get; set; }
    public string? UserId { get; set; }

    // Generated by the saga and passed to Inventory as the reservation aggregate id.
    public Guid ReservationId { get; set; }

    // Token of the scheduled ReservationTimeoutExpired message, so the saga can unschedule it.
    public Guid? TimeoutTokenId { get; set; }

    public string? FailureReason { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}
