using MassTransit;
using SimpleStore.Checkout.API.Timeouts;
using SimpleStore.Contracts;

namespace SimpleStore.Checkout.API.Sagas;

// MassTransit Saga State Machine orchestrating checkout:
//
//   Initial --OrderSubmitted--> AwaitingStock      (publish ReserveStockRequested, schedule timeout)
//   AwaitingStock --StockReserved--> Confirmed     (publish OrderConfirmed)
//   AwaitingStock --StockReservationFailed--> Cancelled  (publish OrderCancelled, reason from msg)
//   AwaitingStock --timeout--> Cancelled           (publish OrderCancelled, reason "ReservationTimeout")
//
// All events correlate on CorrelationId (generated by Order.API). Terminal states Finalize the saga.
//
// TIMEOUT PERSISTENCE: the ReservationTimeout schedule uses the in-memory Quartz scheduler
// (MassTransit.Quartz). Scheduled timeouts do NOT survive a service restart — any saga
// instances in AwaitingStock when the process exits will hang until a matching StockReserved /
// StockReservationFailed arrives. Future work: switch to a durable Quartz job store backed by
// checkoutdb to survive restarts (see docs/checkout-saga.md §11).
public sealed class CheckoutSagaStateMachine : MassTransitStateMachine<CheckoutSagaState>
{
    public State AwaitingStock { get; private set; } = null!;
    public State Confirmed { get; private set; } = null!;
    public State Cancelled { get; private set; } = null!;

    public Event<OrderSubmittedEvent> OrderSubmitted { get; private set; } = null!;
    public Event<StockReservedEvent> StockReserved { get; private set; } = null!;
    public Event<StockReservationFailedEvent> StockReservationFailed { get; private set; } = null!;

    public Schedule<CheckoutSagaState, ReservationTimeoutExpired> ReservationTimeout { get; private set; } = null!;

    public CheckoutSagaStateMachine(IConfiguration configuration)
    {
        InstanceState(x => x.CurrentState);

        var timeoutSeconds = configuration.GetValue<int?>("Checkout:ReservationTimeoutSeconds") ?? 30;

        Event(() => OrderSubmitted, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));
        Event(() => StockReserved, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));
        Event(() => StockReservationFailed, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));

        Schedule(() => ReservationTimeout, x => x.TimeoutTokenId, s =>
        {
            s.Delay = TimeSpan.FromSeconds(timeoutSeconds);
            s.Received = r => r.CorrelateById(ctx => ctx.Message.CorrelationId);
        });

        Initially(
            When(OrderSubmitted)
                .Then(ctx =>
                {
                    ctx.Saga.OrderId = ctx.Message.OrderId;
                    ctx.Saga.UserId = ctx.Message.UserId;
                    ctx.Saga.ReservationId = Guid.NewGuid();
                    ctx.Saga.CreatedAt = DateTime.UtcNow;
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                })
                .Schedule(ReservationTimeout, ctx => new ReservationTimeoutExpired { CorrelationId = ctx.Saga.CorrelationId })
                .Publish(ctx => new ReserveStockRequestedEvent
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    ReservationId = ctx.Saga.ReservationId,
                    OrderId = ctx.Saga.OrderId,
                    RequestedAt = DateTimeOffset.UtcNow,
                    Lines = ctx.Message.Items
                        .Select(i => new ReservationLineItem { ProductId = i.ProductId, Quantity = i.Quantity })
                        .ToList()
                })
                .TransitionTo(AwaitingStock));

        During(AwaitingStock,
            When(StockReserved)
                .Unschedule(ReservationTimeout)
                .Then(ctx => ctx.Saga.UpdatedAt = DateTime.UtcNow)
                .Publish(ctx => new OrderConfirmedEvent
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    ReservationId = ctx.Saga.ReservationId,
                    ConfirmedAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Confirmed)
                .Finalize(),
            When(StockReservationFailed)
                .Unschedule(ReservationTimeout)
                .Then(ctx =>
                {
                    ctx.Saga.FailureReason = ctx.Message.Reason;
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                })
                .Publish(ctx => new OrderCancelledEvent
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    Reason = ctx.Message.Reason,
                    CancelledAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Cancelled)
                .Finalize(),
            When(ReservationTimeout.Received)
                .Then(ctx =>
                {
                    ctx.Saga.FailureReason = "ReservationTimeout";
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                })
                .Publish(ctx => new OrderCancelledEvent
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    Reason = "ReservationTimeout",
                    CancelledAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Cancelled)
                .Finalize());

        // Remove finalized saga instances from checkoutdb. Flip to keep them for audit.
        SetCompletedWhenFinalized();
    }
}
