using System.Diagnostics;
using MassTransit;
using SimpleStore.Checkout.API.Timeouts;
using SimpleStore.Contracts;

namespace SimpleStore.Checkout.API.Sagas;

// MassTransit Saga State Machine orchestrating checkout:
//
//   Initial --OrderSubmitted--> AwaitingStock      (publish ReserveStockRequested, schedule timeout)
//   AwaitingStock --StockReserved--> Confirmed     (publish OrderConfirmed)
//   AwaitingStock --StockReservationFailed--> Cancelled  (publish OrderCancelled, reason from msg)
//   AwaitingStock --timeout--> Cancelled           (publish OrderCancelled, reason "ReservationTimeout")
//
// All events correlate on CorrelationId (generated by Order.API). Terminal states Finalize the saga.
//
// TIMEOUT PERSISTENCE: the ReservationTimeout schedule is backed by a Quartz PERSISTENT ADO store
// in checkoutdb (the qrtz_* tables — see Program.cs and the AddQuartzTables migration). Scheduled
// timeouts SURVIVE a Checkout.API restart: on boot Quartz reloads pending triggers and fires any
// that misfired while the process was down, so a saga left in AwaitingStock is still cancelled.
public sealed class CheckoutSagaStateMachine : MassTransitStateMachine<CheckoutSagaState>
{
    public State AwaitingStock { get; private set; } = null!;
    public State Confirmed { get; private set; } = null!;
    public State Cancelled { get; private set; } = null!;

    public Event<OrderSubmittedEventV1> OrderSubmitted { get; private set; } = null!;
    public Event<StockReservedEventV1> StockReserved { get; private set; } = null!;
    public Event<StockReservationFailedEventV1> StockReservationFailed { get; private set; } = null!;

    public Schedule<CheckoutSagaState, ReservationTimeoutExpired> ReservationTimeout { get; private set; } = null!;

    private readonly ILogger<CheckoutSagaStateMachine> _log;

    public CheckoutSagaStateMachine(IConfiguration configuration, ILogger<CheckoutSagaStateMachine> log)
    {
        _log = log;
        InstanceState(x => x.CurrentState);

        var timeoutSeconds = configuration.GetValue<int?>("Checkout:ReservationTimeoutSeconds") ?? 30;

        Event(() => OrderSubmitted, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));
        Event(() => StockReserved, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));
        Event(() => StockReservationFailed, e => e.CorrelateById(ctx => ctx.Message.CorrelationId));

        Schedule(() => ReservationTimeout, x => x.TimeoutTokenId, s =>
        {
            s.Delay = TimeSpan.FromSeconds(timeoutSeconds);
            s.Received = r => r.CorrelateById(ctx => ctx.Message.CorrelationId);
        });

        Initially(
            When(OrderSubmitted)
                .Then(ctx =>
                {
                    ctx.Saga.OrderId = ctx.Message.OrderId;
                    ctx.Saga.UserId = ctx.Message.UserId;
                    ctx.Saga.ReservationId = Guid.NewGuid();
                    ctx.Saga.CreatedAt = DateTime.UtcNow;
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    // v10: log + tag the transition. The MassTransit consumer-dispatch span is the
                    // current Activity here (auto-emitted once §1 added AddSource("MassTransit"));
                    // tagging it adds the business label without nesting a redundant span.
                    LogTransition(ctx.Saga, "Initial", "AwaitingStock", reason: null);
                })
                .Schedule(ReservationTimeout, ctx => new ReservationTimeoutExpired { CorrelationId = ctx.Saga.CorrelationId })
                .Publish(ctx => new ReserveStockRequestedEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    ReservationId = ctx.Saga.ReservationId,
                    OrderId = ctx.Saga.OrderId,
                    RequestedAt = DateTimeOffset.UtcNow,
                    Lines = ctx.Message.Items
                        .Select(i => new ReservationLineItem { ProductId = i.ProductId, Quantity = i.Quantity })
                        .ToList()
                })
                .TransitionTo(AwaitingStock));

        During(AwaitingStock,
            When(StockReserved)
                .Unschedule(ReservationTimeout)
                .Then(ctx =>
                {
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "AwaitingStock", "Confirmed", reason: null);
                })
                .Publish(ctx => new OrderConfirmedEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    ReservationId = ctx.Saga.ReservationId,
                    ConfirmedAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Confirmed)
                .Finalize(),
            When(StockReservationFailed)
                .Unschedule(ReservationTimeout)
                .Then(ctx =>
                {
                    ctx.Saga.FailureReason = ctx.Message.Reason;
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "AwaitingStock", "Cancelled", reason: ctx.Message.Reason);
                })
                .Publish(ctx => new OrderCancelledEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    Reason = ctx.Message.Reason,
                    CancelledAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Cancelled)
                .Finalize(),
            When(ReservationTimeout.Received)
                .Then(ctx =>
                {
                    ctx.Saga.FailureReason = "ReservationTimeout";
                    ctx.Saga.UpdatedAt = DateTime.UtcNow;
                    LogTransition(ctx.Saga, "AwaitingStock", "Cancelled", reason: "ReservationTimeout");
                })
                .Publish(ctx => new OrderCancelledEventV1
                {
                    CorrelationId = ctx.Saga.CorrelationId,
                    OrderId = ctx.Saga.OrderId,
                    Reason = "ReservationTimeout",
                    CancelledAt = DateTimeOffset.UtcNow
                })
                .TransitionTo(Cancelled)
                .Finalize());

        // Remove finalized saga instances from checkoutdb. Flip to keep them for audit.
        SetCompletedWhenFinalized();
    }

    private void LogTransition(CheckoutSagaState saga, string from, string to, string? reason)
    {
        // Logs feed the Aspire dashboard's log view; the tags feed the trace view. Both share
        // the same CorrelationId so filtering by it joins them up across all participating services.
        if (reason is null)
        {
            _log.LogInformation(
                "Saga {CorrelationId} order {OrderId}: {FromState} -> {ToState}.",
                saga.CorrelationId, saga.OrderId, from, to);
        }
        else
        {
            _log.LogInformation(
                "Saga {CorrelationId} order {OrderId}: {FromState} -> {ToState} ({Reason}).",
                saga.CorrelationId, saga.OrderId, from, to, reason);
        }

        var activity = Activity.Current;
        if (activity is not null)
        {
            activity.SetTag("saga.correlation_id", saga.CorrelationId);
            activity.SetTag("saga.order_id", saga.OrderId);
            activity.SetTag("saga.state.from", from);
            activity.SetTag("saga.state.to", to);
            if (reason is not null) activity.SetTag("saga.cancel_reason", reason);
        }
    }
}
