// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleStore.Inventory.API.Data;

#nullable disable

namespace SimpleStore.Inventory.API.Migrations
{
    [DbContext(typeof(InventoryReadDbContext))]
    [Migration("20260526165224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.DeliveryNoteLineRow", b =>
                {
                    b.Property<Guid>("DeliveryNoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("DeliveryNoteId", "LineNumber");

                    b.ToTable("delivery_note_lines", (string)null);
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.DeliveryNoteRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("delivery_notes", (string)null);
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.ProjectionCheckpointRow", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("CommitPosition")
                        .HasColumnType("bigint");

                    b.Property<long>("PreparePosition")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjectionName");

                    b.ToTable("projection_checkpoints", (string)null);
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.ReceiptNoteLineRow", b =>
                {
                    b.Property<Guid>("ReceiptNoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ReceiptNoteId", "LineNumber");

                    b.ToTable("receipt_note_lines", (string)null);
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.ReceiptNoteRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("receipt_notes", (string)null);
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.StockLevelRow", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastMovementAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OnHand")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("stock_levels", (string)null);
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.StockMovementRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceNoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_stock_movements_product_occurred");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.DeliveryNoteLineRow", b =>
                {
                    b.HasOne("SimpleStore.Inventory.API.Data.ReadModels.DeliveryNoteRow", null)
                        .WithMany("Lines")
                        .HasForeignKey("DeliveryNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.ReceiptNoteLineRow", b =>
                {
                    b.HasOne("SimpleStore.Inventory.API.Data.ReadModels.ReceiptNoteRow", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReceiptNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.DeliveryNoteRow", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SimpleStore.Inventory.API.Data.ReadModels.ReceiptNoteRow", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
